spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update

logging.level.org.hibernate.SQL: DEBUG

access-token.jwt:
  issuer: recompiled-demo.pl
  secret: j+x1Wvn/Dz/AZOqFj/nBsSOUKutXQvhag55MpLESVtI=
  token-lifespan-seconds: 1800